### ISSUE TITLE
Dependency on @quasar/colorize

### ISSUE THREAD

**Issue by eyedean** [quasarframework/quasar-ui-qribbon#14]
While the instruction says `quasar ext add @quasar/qribbon` is the command to install, there is a dependency to `@quasar/colorize` that requires manual `add`, or it fails.  

Maybe the instruction can be improved or `quasar ext add` can become smarter to detect the dependencies and install them automatically.

**Comment by webnoob** [comment]
@hawkeye64 Would you expect this as a result of your changes? I can take a look when I'm back home.

**Comment by hawkeye64** [comment]
This is what happens when one AE is dependent on another. In discussions with @rstoenescu on how best to handle this. I'd like it to automatically install, but he's worried about circular dependencies.

The other thing is to PR against @quasar/app, to change the dependency function so a custom message can be used.

**Comment by hawkeye64** [comment]
This has no longer been an issue since the last release of QRibbon (v1.0.0-beta.8)
